package com.myspace.example1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ItemGroup implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String category;

	private java.math.BigDecimal totalPrice;

	public ItemGroup() {
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.math.BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	public ItemGroup(java.lang.String category, java.math.BigDecimal totalPrice) {
		this.category = category;
		this.totalPrice = totalPrice;
	}

}