package com.myspace.dmnexample1;

import java.util.ArrayList;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class EntityList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> name = new ArrayList();

	public EntityList() {
	}

	public java.util.List<java.lang.String> getName() {
		return this.name;
	}

	public void setName(java.util.List<java.lang.String> name) {
		this.name = name;
	}

	public EntityList(java.util.List<java.lang.String> name) {
		this.name = name;
	}

}