package com.myspace.example1;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Item implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("category")
	private java.lang.String category;
	@org.kie.api.definition.type.Label("price")
	private BigDecimal price;
	public Item() {
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.math.BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(java.math.BigDecimal price) {
		this.price = price;
	}

	public Item(java.lang.String category, java.math.BigDecimal price) {
		this.category = category;
		this.price = price;
	}

}