package com.myspace.example1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ItemsList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "items")
	private java.util.List<com.myspace.example1.Item> items;

	public ItemsList() {
	}

	public java.util.List<com.myspace.example1.Item> getItems() {
		return this.items;
	}

	public void setItems(java.util.List<com.myspace.example1.Item> items) {
		this.items = items;
	}

	public ItemsList(java.util.List<com.myspace.example1.Item> items) {
		this.items = items;
	}

}