package com.myspace.example1;

/**
 * This class was automatically generated by the data modeler tool.
 */

import java.util.HashMap;

public class Sample implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String field1;
    public HashMap data = null;

	public Sample() {
		data = new HashMap();
	}

	public void putData(String key, String value) {
		data.put(key, value);
	}

	public HashMap getData() {
		return data;
	}

	public java.lang.String getField1() {
		return this.field1;
	}

	public void setField1(java.lang.String field1) {
		this.field1 = field1;
	}

	public Sample(java.lang.String field1) {
		this.field1 = field1;
	}

}