package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Reason implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String reasonId;
	private java.lang.String reason;
	private int score;

	public Reason() {
	}

	public java.lang.String getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(java.lang.String reasonId) {
		this.reasonId = reasonId;
	}

	public java.lang.String getReason() {
		return this.reason;
	}

	public void setReason(java.lang.String reason) {
		this.reason = reason;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public Reason(java.lang.String reasonId, java.lang.String reason, int score) {
		this.reasonId = reasonId;
		this.reason = reason;
		this.score = score;
	}

}